[theme]
font = "'Albert Sans':https://fonts.googleapis.com/css2?family=Albert+Sans:ital,wght@0,100..900;1,100..900&family=IBM+Plex+Sans:ital,wdth,wght@0,75,700;1,75,700&display=swap"
primaryColor = "#2bc2ae"
